app = "tigris-registry"

[build]
image = "registry:2"

[mounts]
source = "htpasswd"
destination = "/data"
initial_size = 1

[[services]]
protocol = "tcp"
internal_port = 5000
processes = ["app"]
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 750

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
